# NOTE:
# - change APP_BASE_URL, POSTGRES_PASSWORD, and POSTGRES_HOST in accordance with your needs
# - change volumes path according to your needs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin_environment
data:
  APP_BASE_URL: https://joplin.local:5555
  APP_PORT: 1025
  DB_CLIENT: pg
  POSTGRES_PASSWORD: 1JTewDVUBBucB9GTRwJk1Szo2YRDDd
  POSTGRES_DATABASE: joplin
  POSTGRES_USER: joplin
  POSTGRES_PORT: 5432
  POSTGRES_HOST: 192.168.80.128
  MAX_TIME_DRIFT: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres_environment
data:
  POSTGRES_PASSWORD: 1JTewDVUBBucB9GTRwJk1Szo2YRDDd
  POSTGRES_USER: joplin
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: joplin
  name: joplin
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data:Z
          name: postgre_data
      envFrom:
        - configMapRef:
            name: postgres_environment
          resources: {}
    - name: server
      image: joplin/server:latest
      ports:
        - containerPort: 1025
          hostPort: 1025
      envFrom:
        - configMapRef:
            name: joplin_environment
      resources: {}
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 5555
          hostPort: 5555
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/joplin.conf:Z
          name: nginx_configuration
        - mountPath: /etc/ssl/certs/:Z
          name: nginx_ssl_certificates
  volumes:
    # change this path directory according to your needs
    - name: postgre_data
      hostPath:
        path: /home/ringo/joplin/postgres/data
        type: Directory
    - name: nginx_configuration
      hostPath:
        Path: /home/ringo/joplin/nginx/nginx.conf
        type: File
    - name: nginx_ssl_certificates
      hostPath:
        Path: /home/ringo/joplin/nginx/certs/
        type: Directory